### ISSUE TITLE
KLA data import

### ISSUE THREAD

**Issue by HughP** [HughP/tcf-james-bigramed#3]
@iandoug How do I go from http://www.keyboard-layout-editor.com/ JSON to KLA JSON?

**Comment by iandoug** [comment]
With difficulty :-)
Entirely different animals I'm afraid.
I have a program that goes the other way, for ANSI layouts. But it cheats a bit, in knowing that it's working with an ANSI/ISO/Ergodox/etc layout. It then generates the JSON for KLE.

Going from KLE to KLA is on the to-do/wishlist ... in truth at the moment there are only four/five defined layouts in KLA, so the layout in KLE would have to be one of them.

So regret at the moment you have to go via the wetware behind the keyboard.... :-)

The other problem is that KLE provides 12 slots on each key, and KLA only 4. So the KLE design would to be pedantic about only using the four corner slots. As well as defining upper and lower case every time.

Tedious I know.

I'll move the KLE2KLA script from the back burner to the middle burner... some issues probably need to be thunk through some more.

**Comment by HughP** [comment]
KLE2KLA should get its own repo. It is its own project.

**Comment by iandoug** [comment]
> KLE2KLA should get its own repo. It is its own project.

Am giving it a go. Looks like will work, at least for form factors that KLA knows about, and with rather stringent restrictions. Thou shalt not move the keys around, and thou shalt not relabel the non-alphanumeric keys. (well for now anyway).
 KLE is very anything-goes, but KLA is not. And the conversion program can't guess what you meant. 
Hope to have it working tomorrow, at least for ANSI 104.
