### ISSUE TITLE
Initial observations

### ISSUE THREAD

**Issue by iandoug** [HughP/tcf-james-bigramed#4]
Had a VERY quick look at this.
Some thoughts/whatever

1. current layout using QWERTY is clearly not optimal, the right pinkies are way overworked. As is left on A.
2. I'm guessing an optimised layout for this language would put  those characters on the thumbs or middle fingers at least.
3. all the \x stuff on the left should be stripped from the test corpus.
4. this is a bit bizarre:
	a 2975
	  2742
	' 2233
	[ 1835
	i 1539
	n 1606
	\ 1189
	u 1158
There are more letter A than spaces? And almost as many ' tone marks as spaces?
Looks like the language revolves around a i n u and tone? :-)

Let me try a few things...

**Comment by HughP** [comment]
Did I not mention that number 3 is done?
