### ISSUE TITLE
The underline

### ISSUE THREAD

**Issue by iandoug** [HughP/tcf-james-bigramed#5]
e̱ ... is that U+0320 COMBINING MINUS SIGN BELOW or U+0331 COMBINING MACRON BELOW  or U+0332 COMBINING LOW LINE?
Or something else?

**Comment by HughP** [comment]
I put a file with all the Unicode points and their counts in the corpus. See here: https://github.com/HughP/tcf-james-bigramed/blob/master/mephaa-Unicode-usage.txt
