### ISSUE TITLE
Odd chars

### ISSUE THREAD

**Issue by iandoug** [HughP/tcf-james-bigramed#8]
Hi

Picking up one  Ꞌ U+A78B LATIN CAPITAL LETTER SALTILLO

Should that be the lower case one?

**Comment by HughP** [comment]
Nope! This is the language that they added that character to Unicode for.
It is actually a contrastive word initial glottal stop. It is a real letter
and it is Uppercase.

**Comment by iandoug** [comment]
So noted. :-)
Have put it as shifted on the lower case one.
Will upload some layouts shortly.
