### ISSUE TITLE
fonts ...

### ISSUE THREAD

**Issue by iandoug** [HughP/tcf-james-bigramed#9]
Hi

What fonts do you guys use for tcf?

Trying to modify my font-checker program to also check suitability for tcf, and noticed that Doulos does not always align the under macron nicely. Was just wondering if this is some quirk on my system or a general issue.

Screenshot:
![screenshot_20180627_133139](https://user-images.githubusercontent.com/12673886/41971407-976dd2ec-7a0e-11e8-98b1-2a333f6008e3.png)

**Comment by iandoug** [comment]
I checked a bunch of other fonts (ones that work with Dan) and they all showed various degrees of mis-alignment ... I am using ̱U+0331 COMBINING MACRON BELOW

**Comment by HughP** [comment]
I think the Unicode prescribed ideal for U+0331 is off center. see discussion here: https://en.wikipedia.org/wiki/Macron_below

**Comment by iandoug** [comment]
Starting to wonder if it is perhaps something to do with TTF vs OTF, where more modern OTF handles them better.

**Comment by HughP** [comment]
Font designers wrote to me and told me that they have a randomizer in their font, because they don't know what is the best alignment, but they would like the technical details on how you made that image where it shows up like that.... see private email.
